### ISSUE TITLE
테스트 프레임워크 적용

### ISSUE THREAD

**Issue by sooster910** [f-lab-edu/airbnb-clone#16]
##  테스트 프레임워크 선정

**선정 기준** 

- Next.js와 설치 호환성이 좋아야 함
- Test 개발 경험이 없는 개발자의 역량 향상을 위해 시장에서 많이 사용하는 툴 선호
- Community 지원과 참고할 수 있는 문서들이 많은 툴 선호

**Next.js 공식문서 테스트 유형 참고** 

1. Unit Testing
    - Component testing
    - Intergration testing
2. End-to-End(E2E) Testing
3. Snapshot Testing

**Next.js 14 App router 에서 제안한 보편적인 툴**  <[공식문서](https://nextjs.org/docs/app/building-your-application/styling) 참고>

- vitest - Unit Testing
- Jest - Unit Testing, Snapshot Testing
- Playwright - e2e
- Cypress -e2e

**Unit Testing Tool NPM trend 비교**  

<img width="1183" alt="testing_framework_npmtrend" src="https://github.com/f-lab-edu/airbnb-clone/assets/26635607/19dad156-7327-456a-8684-774e45d860c7">

**결과**

- Vitest가 설치 과정이 Jest보다 단순하지만 시장에서 더 많이 사용 되고 있는 툴은 Jest 이므로, Jest를 통해 테스트 작성에 익숙해진 후 Vitest로 전환하거나 추가 해도 좋을 것 같다.
- Nextjs 공식문서에서 Jest는 비동기 서버 컴포넌트를 지원하지 않아 E2E 테스트를 사용하는 것이 좋다고 권장하는데 어떤 의미인지 와닿지 않아 **실제 상황에 마주 했을 때 재고민**

**Comment by gotama3** [comment]
Nextjs 공식문서에서 Jest는 비동기 서버 컴포넌트를 지원하지 않아 E2E 테스트를 사용하는 것이 좋다고 권장하는 부분 어디인지 공유해주실수 있을까요? 저도 선뜻 이해가 안가네요

**Comment by sooster910** [comment]
> Nextjs 공식문서에서 Jest는 비동기 서버 컴포넌트를 지원하지 않아 E2E 테스트를 사용하는 것이 좋다고 권장하는 부분 어디인지 공유해주실수 있을까요? 저도 선뜻 이해가 안가네요

네 링크 공유 드릴게요. [Next Jest 테스트 공식문서 바로가기](https://nextjs.org/docs/app/building-your-application/testing/jest)  
아래와 같은 내용인데요. vitest섹션도 마찬가지로 같이 적혀있어요. 

<img width="600" alt="image" src="https://github.com/f-lab-edu/airbnb-clone/assets/26635607/a2c4b805-02a0-4eef-9336-cbd14bf5fa48">

**Comment by gotama3** [comment]
> > Nextjs 공식문서에서 Jest는 비동기 서버 컴포넌트를 지원하지 않아 E2E 테스트를 사용하는 것이 좋다고 권장하는 부분 어디인지 공유해주실수 있을까요? 저도 선뜻 이해가 안가네요
> 
> 네 링크 공유 드릴게요. [Next Jest 테스트 공식문서 바로가기](https://nextjs.org/docs/app/building-your-application/testing/jest) 아래와 같은 내용인데요. vitest섹션도 마찬가지로 같이 적혀있어요.
> 
> <img alt="image" width="600" src="https://private-user-images.githubusercontent.com/26635607/336009236-a2c4b805-02a0-4eef-9336-cbd14bf5fa48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0OTMyMTAsIm5iZiI6MTcxNzQ5MjkxMCwicGF0aCI6Ii8yNjYzNTYwNy8zMzYwMDkyMzYtYTJjNGI4MDUtMDJhMC00ZWVmLTkzMzYtY2JkMTRiZjVmYTQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDA5MjE1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkMWMwOGFmYjQyOGY1NWVjNDU5MTBmYzY3NGFhNDk0MTkxZTVjNTU4ZjhjZTQ2MmExN2I1OGFlYWNmNjNmNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7EVstm-mLx6xGurc43D96zYWuqNdRZyh6upXRoDMa_Y">

ReactServerComponent(RSC) 에서의 비동기 서버 컴포넌트를 이야기하는거네요. 
RSC를구현할 예정은 없기 때문에 신경 안쓰셔도 될 것 같습니다 ~ ㅎㅎ
